use_frameworks!

target 'VCommon_Example' do
  pod 'VCommon', :path => '../'

  target 'VCommon_Tests' do
    inherit! :search_paths
  end
  target 'V_ColorTests' do
    inherit! :search_paths
  end
  target 'V_DateTests' do
      inherit! :search_paths
  end
  
end
