use_frameworks!

target 'VCommon_Example' do
  pod 'VCommon', :path => '../'

  target 'VCommon_Tests' do
    inherit! :search_paths
  end
  target 'V_ColorTests' do
    inherit! :search_paths
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.2'
          end
      end
  end
  
end
